cli: User data command
projectatomic/commctl pull request #33
Opened 2017-04-10 20:26 UTC by ashcrow

- Rearanges the helper commands in ``commctl``
- Adds ``user-data`` to replace much of [these](http://commissaire.readthedocs.io/en/latest/cloud_init.html) manual steps
- Adds in data files to generate the user-data output

A follow on for ``commissaire`` to update docs will be done once this merges.

## Example
```
$ commctl user-data --password -u my_commissaire_user \
   -e http://api.example.com \
   output.userdata
Password:
```

/cc @tbielawa

2017-04-11 22:17 UTC, mbarnes requested changes
One minor request (if you agree), otherwise looks good.

2017-04-11 22:17 UTC, mbarnes commented on src/commctl/client_script.py
> +        help='Path and file name to output the user-data contents')
I'd prefer writing to standard output by default, and maybe have a `-o / --output FILE` convenience option.

2017-04-12 13:39 UTC, ashcrow commented on src/commctl/client_script.py
> +        help='Path and file name to output the user-data contents')
Fair enough. Will update.

2017-04-12 13:47 UTC, ashcrow commented
⬆️

2017-04-12 14:27 UTC, mbarnes approved these changes
Looks good!  :+1:

One tiny nit.  Assuming you agree with it, I can just change it myself since I have to manually squash this anyway.

2017-04-12 14:27 UTC, mbarnes commented on src/commctl/client_script.py
> +        '-o', '--outfile', help='Output file. If empty STDOUT is used')
tiny nit: I think "omitted" would be clearer than "empty" here

2017-04-12 14:36 UTC, ashcrow commented
⬆️

2017-04-12 14:40 UTC, mbarnes commented
Squashed and merged manually.

2017-04-12 14:40 UTC, closed without merging